### ISSUE TITLE
How to submit model results to T-Eval?

### ISSUE THREAD

**Issue by magicsongyang** [open-compass/T-Eval#1]

**Comment by zehuichen123** [comment]
Hi, thanks for your attention! We will release a detailed submission instruction soon. You may follow that~

**Comment by zehuichen123** [comment]
@magicsongyang Hi, we have updated a detailed instruction to run T-Eval and how to submit results to our leaderboard. (https://github.com/open-compass/T-Eval?tab=readme-ov-file#%EF%B8%8F-submit-your-results)

**Comment by magicsongyang** [comment]
OK, thanks.
