### ISSUE TITLE
cannot import name 'HFTransformerChat' from 'lagent.llms.huggingface

### ISSUE THREAD

**Issue by xjwhy** [open-compass/T-Eval#24]
作者你好，跑v0.2代码的时候，报上面的错误，我看lagent里的确没有 HFTransformerChat https://github.com/InternLM/lagent/blob/main/lagent/llms/huggingface.py，如何解决？

**Comment by zehuichen123** [comment]
目前的code还没有pr到lagent里面 在这个branch上 https://github.com/InternLM/lagent/pull/157，预计今天会合进去～

**Comment by zehuichen123** [comment]
@xjwhy 已经合入了～
